In [2]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, average_precision_score
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import numpy as np



In [3]:
def LogisticRegressionModel(dataset,name):
    x = dataset.data
    y = dataset.target  # Changed from dataset.data to dataset.target
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
    logreg = LogisticRegression(max_iter=1000 ,solver='liblinear')
    logreg.fit(x_train, y_train)
    y_pred = logreg.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("The accuracy and precision for ",name)
    print(f'Accuracy: {accuracy}')
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f'Confusion Matrix:\n {conf_matrix}')
    y_score = logreg.decision_function(x_test)
    avg_precision = average_precision_score(y_test, y_score)
    print(f'Average Precision for : {avg_precision}\n')

In [4]:
##For Toy Dataset
from sklearn.datasets import load_iris
from sklearn.datasets import load_digits
from sklearn.datasets import load_wine
from sklearn.datasets import load_breast_cancer

# Load the  dataset
iris = load_iris()
digits=load_digits()
wine=load_wine()
breast=load_breast_cancer()

# Call the function with the iris dataset
LogisticRegressionModel(iris,"iris\n")
LogisticRegressionModel(digits,"digits\n")
LogisticRegressionModel(wine,"wine\n")
LogisticRegressionModel(breast,"breast\n")


The accuracy and precision for  iris

Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Average Precision for : 0.8583086504139135

The accuracy and precision for  digits

Accuracy: 0.9611111111111111
Confusion Matrix:
 [[33  0  0  0  0  0  0  0  0  0]
 [ 0 27  0  0  0  0  0  0  1  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  1  0  0 44  0  1  0  0  0]
 [ 0  0  1  0  0 45  1  0  0  0]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  1  0  0  0  1  0  0 28  0]
 [ 0  0  0  0  0  0  0  0  4 36]]
Average Precision for : 0.9778777258812484

The accuracy and precision for  wine

Accuracy: 0.9722222222222222
Confusion Matrix:
 [[13  1  0]
 [ 0 14  0]
 [ 0  0  8]]
Average Precision for : 0.9967120181405895

The accuracy and precision for  breast

Accuracy: 0.956140350877193
Confusion Matrix:
 [[39  4]
 [ 1 70]]
Average Precision for : 0.9986451224185282



In [5]:
#For Real Time Dataset
from sklearn.datasets import fetch_olivetti_faces
from sklearn.datasets import fetch_20newsgroups
from sklearn.datasets import fetch_20newsgroups_vectorized
from sklearn.datasets import fetch_lfw_pairs
from sklearn.datasets import fetch_lfw_people
from sklearn.datasets import fetch_covtype
from sklearn.datasets import fetch_rcv1
from sklearn.datasets import fetch_kddcup99


faces=fetch_olivetti_faces()
newsGroup=fetch_20newsgroups()
newsGroup_vectorized=fetch_20newsgroups_vectorized()
paris=fetch_lfw_pairs()
people=fetch_lfw_people()
covtype=fetch_covtype()
rcv1=fetch_rcv1()
kddcup=fetch_kddcup99()



# LogisticRegressionModel(faces,"faces\n")
LogisticRegressionModel(newsGroup,"newsGRoup\n")
LogisticRegressionModel(newsGroup_vectorized,"newsGroup_vectorized\n")
LogisticRegressionModel(paris,"paris\n")
LogisticRegressionModel(people,"people\n")
LogisticRegressionModel(covtype,"covtype\n")
LogisticRegressionModel(rcv1,"rcv1\n")
LogisticRegressionModel(kddcup,"kddcup\n")



KeyboardInterrupt: 

In [66]:
def LogisticRegressionModel2(dataset, name):
    x, y = dataset  # Unpack the data and target from the tuple
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
    logreg = LogisticRegression()
    logreg.fit(x_train, y_train)
    y_pred = logreg.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("The accuracy for ", name)
    print(f'Accuracy: {accuracy}')
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f'Confusion Matrix:\n {conf_matrix}')
    avg_precision = average_precision_score(y_test, y_pred, average="macro")
    print(f'Average Precision: {avg_precision}')




In [67]:
#For Synthetic Dataset
from sklearn.datasets import make_circles
from sklearn.datasets import make_moons

moons=make_moons()
circles=make_circles()


LogisticRegressionModel2(circles,"circles\n")
LogisticRegressionModel2(moons,"moons\n")



The accuracy for  circles

Accuracy: 0.45
Confusion Matrix:
 [[7 2]
 [9 2]]
Average Precision: 0.5409090909090909
The accuracy for  moons

Accuracy: 0.95
Confusion Matrix:
 [[ 9  0]
 [ 1 10]]
Average Precision: 0.9590909090909091
